apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-creator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-creator-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-creator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: service-creator
    namespace: default
roleRef:
  kind: Role
  name: service-creator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.16.1
        args:
        - --source=service
        - --provider=rfc2136
        - --rfc2136-host=192.168.1.29
        - --rfc2136-port=53
        - --rfc2136-zone=myservices.local
        - --rfc2136-insecure
        - --domain-filter=myservices.local
        - --log-level=debug

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmxsafe-gw
spec:
  replicas: 3  # Three pod replicas simulating CMX-GWs
  selector:
    matchLabels:
      app: cmxsafe-gw
  template:
    metadata:
      labels:
        app: cmxsafe-gw
    spec:
      serviceAccountName: service-creator
      volumes:
        - name: ssh-keys
          configMap:
            name: ssh-keys
        - name: scripts
          configMap:
            name: scripts
      containers:
      - name: cmxsafe-gw
        image: ubuntu:20.04  # Use a stable image
        securityContext:
          privileged: true  # Needed for iptables manipulation
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 22   # SSH Primary
        - containerPort: 2222 # SSH Secondary
        volumeMounts:
        - mountPath: /tmp/ssh-keys
          name: ssh-keys
        - mountPath: /tmp/scripts
          name: scripts
        command: ["/bin/bash", "-c"]
        args:
          - |
            
            apt-get update && apt-get install -y curl;

            curl -LO "https://dl.k8s.io/release/$(curl -L https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && mv kubectl /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl;
            kubectl label pods "$MY_POD_NAME" pod-name="$MY_POD_NAME"

            echo "KUBERNETES_SERVICE_PORT_HTTPS=$KUBERNETES_SERVICE_PORT_HTTPS" >> /etc/environment
            echo "CMXSAFE_GW_SERVICE_PORT_SSH_SECONDARY=$CMXSAFE_GW_SERVICE_PORT_SSH_SECONDARY" >> /etc/environment
            echo "KUBERNETES_SERVICE_PORT=$KUBERNETES_SERVICE_PORT" >> /etc/environment
            echo "HOSTNAME=$HOSTNAME" >> /etc/environment
            echo "CMXSAFE_GW_PORT_2222_TCP_PROTO=$CMXSAFE_GW_PORT_2222_TCP_PROTO" >> /etc/environment
            echo "CMXSAFE_GW_SERVICE_PORT_SSH_PRIMARY=$CMXSAFE_GW_SERVICE_PORT_SSH_PRIMARY" >> /etc/environment
            echo "CMXSAFE_GW_PORT_2222_TCP_PORT=$CMXSAFE_GW_PORT_2222_TCP_PORT" >> /etc/environment
            echo "CMXSAFE_GW_SERVICE_PORT=$CMXSAFE_GW_SERVICE_PORT" >> /etc/environment
            echo "KUBERNETES_PORT_443_TCP=$KUBERNETES_PORT_443_TCP" >> /etc/environment
            echo "CMXSAFE_GW_PORT=$CMXSAFE_GW_PORT" >> /etc/environment
            echo "CMXSAFE_GW_PORT_22_TCP=$CMXSAFE_GW_PORT_22_TCP" >> /etc/environment
            echo "CMXSAFE_GW_PORT_22_TCP_ADDR=$CMXSAFE_GW_PORT_22_TCP_ADDR" >> /etc/environment
            echo "MY_POD_NAME=$MY_POD_NAME" >> /etc/environment
            echo "KUBERNETES_PORT_443_TCP_PROTO=$KUBERNETES_PORT_443_TCP_PROTO" >> /etc/environment
            echo "KUBERNETES_PORT_443_TCP_ADDR=$KUBERNETES_PORT_443_TCP_ADDR" >> /etc/environment
            echo "CMXSAFE_GW_PORT_2222_TCP=$CMXSAFE_GW_PORT_2222_TCP" >> /etc/environment
            echo "KUBERNETES_SERVICE_HOST=$KUBERNETES_SERVICE_HOST" >> /etc/environment
            echo "KUBERNETES_PORT=$KUBERNETES_PORT" >> /etc/environment
            echo "KUBERNETES_PORT_443_TCP_PORT=$KUBERNETES_PORT_443_TCP_PORT" >> /etc/environment
            echo "CMXSAFE_GW_PORT_22_TCP_PORT=$CMXSAFE_GW_PORT_22_TCP_PORT" >> /etc/environment
            echo "CMXSAFE_GW_SERVICE_HOST=$CMXSAFE_GW_SERVICE_HOST" >> /etc/environment
            echo "CMXSAFE_GW_PORT_22_TCP_PROTO=$CMXSAFE_GW_PORT_22_TCP_PROTO" >> /etc/environment
            echo "CMXSAFE_GW_PORT_2222_TCP_ADDR=$CMXSAFE_GW_PORT_2222_TCP_ADDR" >> /etc/environment

            # Update and install necessary packages
            apt-get update && apt-get install -y openssh-server iputils-arping iptables iproute2 net-tools tcpdump nano supervisor sudo dos2unix;

            # Configure SSHD
            mkdir -p /run/sshd;
            echo "AllowTcpForwarding yes" >> /etc/ssh/sshd_config;
            echo "PermitTunnel yes" >> /etc/ssh/sshd_config;
            echo "GatewayPorts yes" >> /etc/ssh/sshd_config;
            echo "PasswordAuthentication no" >> /etc/ssh/sshd_config;  # Enforce key authentication
            echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config;
            echo "UsePAM no" >> /etc/ssh/sshd_config;
            echo "SyslogFacility AUTH" >> /etc/ssh/sshd_config;
            echo "LogLevel DEBUG3" >> /etc/ssh/sshd_config;

            # Create secondary SSH config (port 2222)
            # cp /etc/ssh/sshd_config /etc/ssh/sshd_config_2;
            # echo "Port 2222" >> /etc/ssh/sshd_config_2;
            # echo "PidFile /var/run/sshd_2.pid" >> /etc/ssh/sshd_config_2;

            # Fix SSH authorized_keys issue
            mkdir -p /root/.ssh
            cp /tmp/ssh-keys/authorized_keys /root/.ssh/authorized_keys
            chmod 700 /root/.ssh
            chmod 600 /root/.ssh/authorized_keys
            chown -R root:root /root/.ssh

            # Scripts
            mkdir -p /etc/cmxsafe_scripts
            chmod 755 /etc/cmxsafe_scripts
            chown root:root /etc/cmxsafe_scripts
            cp /tmp/scripts/createservice.sh /etc/cmxsafe_scripts/createservice.sh
            dos2unix /etc/cmxsafe_scripts/createservice.sh
            chmod 755 /etc/cmxsafe_scripts/createservice.sh

            # Initialize users
            MAC_SRV="a2:3f:f8:68:ec:8f"
            MAC_DEV="02:5f:9a:3d:b7:12"

            # Function to format MAC address (remove colons and convert to uppercase)
            format_mac() {
                echo "$1" | sed 's/://g'
            }

            # Get formatted MAC addresses
            SERVER=$(format_mac "$MAC_SRV")
            DEVICE=$(format_mac "$MAC_DEV")

            for user in "$SERVER" "$DEVICE"; do
                adduser --disabled-password --gecos "" $user --force-badname
                mkdir -p /home/$user/.ssh
                cp /tmp/ssh-keys/authorized_keys /home/$user/.ssh/authorized_keys
                chmod 700 /home/$user/.ssh
                chmod 600 /home/$user/.ssh/authorized_keys
                chown -R $user:$user /home/$user/.ssh
                mkdir -p /home/$user/.kube
                cp /root/.kube/config /home/$user/.kube/config
                chown -R $user:$user /home/a23ff868ec8f/.kube
            done

            echo "Match User $SERVER" >> /etc/ssh/sshd_config;
            echo "    ForceCommand /etc/cmxsafe_scripts/createservice.sh; sleep infinity" >> /etc/ssh/sshd_config;

            #echo "Match User *" >> /etc/ssh/sshd_config_2;
            #echo "    ForceCommand /bin/bash -c 'echo ForcedCommandInvoked >> /tmp/forced_command.log'; sleep infinity" >> /etc/ssh/sshd_config_2;

            sudo service ssh restart;

            # Start SSH server
            /usr/sbin/sshd -f /etc/ssh/sshd_config;
            #/usr/sbin/sshd -f /etc/ssh/sshd_config_2 -d -d -E /tmp/ssh.log;

            # Keep container alive
            tail -f /dev/null;
