apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cmxsafe-gateway-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
  - fd00::240-fd00::250
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cmxsafe-gateway-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - cmxsafe-gateway-pool
  interfaces:
  - eth1