apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "sshd1"
spec:
  podSelector:
    matchLabels:
      app: "cmxsafe-gw"
  kprobes:
  - call: "cap_capable"
    syscall: false
    return: true
    args:
    - index: 1
      type: "user_namespace"
    - index: 2
      type: "capability"
    returnArg:
      index: 0
      type: "int"
    selectors:
      - matchNamespaces:
        - namespace: Pid
          operator: NotIn
          values:
          - "host_ns"
        matchActions:
          - action: Post
            rateLimit: "1m"  # Rate limit messages to 1min